# enrich_questions.py
# Add authentic Databricks code snippets to questions to mirror actual exam questions

import json

# Enrich D1, D2, D3, D4, D567 with realistic code blocks

from questions_d1 import D1_QUESTIONS
from questions_d2 import D2_QUESTIONS
from questions_d3 import D3_QUESTIONS
from questions_d4 import D4_QUESTIONS
from questions_d567 import D567_QUESTIONS
from questions_drill import DRILL_QUESTIONS
from build_rich_guide import RICH_GUIDE_CHAPTERS
from build_data import cheatsheets

# Q1 code
D1_QUESTIONS[0]["code"] = """# MLflow trace captured from support agent:
query = "What is the refund timeline for my purchase?"
retrieved_chunk = {
    "source": "dbfs:/rag/docs/drafts/refund_policy_2024_draft.md",
    "text": "Draft clause: All customers are eligible for 100% full refund within 90 days."
}
# System Prompt:
system_prompt = "Adhere strictly to official company policy: maximum 30 days refund."
# Agent output:
"You are eligible for a 100% full refund within 90 days of purchase.\""""

# Q8 code
D1_QUESTIONS[7]["code"] = """# Enterprise Agent Stack Definition
agent_architecture = {
    "data_governance": "???",       # Requires row/column masking & catalog access
    "state_persistence": "???",     # Multi-session durable memory across restarts
    "tool_protocol": "???",         # Open standard for dynamic tool invocation
    "eval_and_tracing": "???"       # Step-by-step reasoning trace logging
}"""

# Q11 code
D2_QUESTIONS[0]["code"] = """-- Executive Query in Genie Space:
-- "Show me net MRR growth for Q3 2026"

-- Ad-hoc SQL generated by Genie (Incorrect):
SELECT SUM(amount) FROM billing.invoices WHERE quarter = 'Q3_2026';

-- Verified business calculation requires currency normalization and promotion deductions."""

# Q16 code
D2_QUESTIONS[5]["code"] = """# Desired structured response format
from pydantic import BaseModel, Field

class TriageResult(BaseModel):
    status: str = Field(description="Incident resolution status")
    extracted_ids: list[str] = Field(description="Affected customer UUIDs")
    risk_score: float = Field(ge=0.0, le=1.0, description="Severity score")"""

# Q20 code
D2_QUESTIONS[9]["code"] = """-- Failing Delta Lake query generated by SQL agent:
SELECT * FROM sales_catalog.crm.customers WHERE is_active = 'true';
-- AnalysisException: cannot resolve 'is_active = true' due to data type mismatch (TINYINT vs STRING)"""

# Q23 code
D3_QUESTIONS[2]["code"] = """# Current Vector Search Query Configuration:
results = vector_search_client.get_index("catalog.default.parts_index").similarity_search(
    query_text="Find hydraulic fault FAULT_HYD_402 for serial SN-8820-X",
    columns=["part_id", "manual_excerpt"],
    num_results=5
)
# Returns generic hydraulic principles instead of the exact serial number record."""

# Q26 code
D3_QUESTIONS[5]["code"] = """# Vector Search Index Pipeline Configuration
from databricks.vector_search.client import VectorSearchClient
vsc = VectorSearchClient()

index = vsc.create_delta_sync_index(
    endpoint_name="policy_search_endpoint",
    source_table_name="hr_catalog.policies.parental_leave",
    index_name="hr_catalog.policies.parental_leave_index",
    pipeline_type="???",  # What pipeline type prevents stale embeddings?
    primary_key="doc_id",
    embedding_source_column="policy_text"
)"""

# Q33 code
D4_QUESTIONS[2]["code"] = """# Agent State Retrieval Step
# Exact target identifier: user_id = 'USR-90210'
target_user = "USR-90210"

# Option 1: vector_index.similarity_search(query_text=target_user)
# Option 2: spark.table("lakebase.user_profiles").filter(f"user_id = '{target_user}'")"""

# Q36 code
D4_QUESTIONS[5]["code"] = """# Multi-step Agent Orchestration Loop
for step_idx in range(1, 11):
    execute_step(step_idx)
    # Spot instance preemption occurs at step 6!
    # How should execution state be persisted?"""

# Q41 code
D567_QUESTIONS[0]["code"] = """# MCP Tool Registry with 80 enterprise tools
# Initial Prompt Token Count with all full schemas: 38,400 tokens!
# Context window approaching limit before processing turn 1."""

# Q46 code
D567_QUESTIONS[5]["code"] = """# Tool validation error response
# Received invalid argument: date = '2024/05/01'
# Expected ISO 8601: 'YYYY-MM-DD'"""

# Q62 code
D567_QUESTIONS[21]["code"] = """# Subagent Execution Output
# Raw analytical payload: 45 MB structured log records (2,000,000 rows)
# Target: Return findings to parent Orchestrator Agent without blowing token limit."""

# Q66 code
D567_QUESTIONS[25]["code"] = """# Context Handoff Protocol
# Flow: TriageAgent -> FulfillmentAgent
handoff_payload = {
    "origin": "TriageAgent",
    "target": "FulfillmentAgent",
    "canonical_intent": "EXPEDITE_SHIPPING",
    "order_id": "ORD-99120",
    "unfulfilled_items": ["ITEM-44"],
    "trace_id": "tr-7782-b"
}"""

print("Code enhancements successfully mapped.")

# Now rebuild all questions
all_70 = D1_QUESTIONS + D2_QUESTIONS + D3_QUESTIONS + D4_QUESTIONS + D567_QUESTIONS

mock_questions = []
for idx, q in enumerate(all_70[:45]):
    q_copy = dict(q)
    q_copy["id"] = f"Q{idx + 1}"
    q_copy["num"] = idx + 1
    q_copy["type"] = "mock"
    mock_questions.append(q_copy)

practice_questions = []
for idx, q in enumerate(all_70[45:]):
    q_copy = dict(q)
    q_copy["id"] = f"D{idx + 1}"
    q_copy["num"] = idx + 1
    q_copy["type"] = "practice"
    practice_questions.append(q_copy)

exam_data = {
    "guideChapters": RICH_GUIDE_CHAPTERS,
    "cheatsheets": cheatsheets,
    "mockQuestions": mock_questions,
    "practiceQuestions": practice_questions,
    "drillQuestions": DRILL_QUESTIONS
}

js_content = "/**\n * Databricks Certified Context Engineer Associate - Complete Exam Data\n * English Questions & Options, In-Depth Japanese Explanations, Rich Study Guide\n */\n"
js_content += "window.EXAM_DATA = " + json.dumps(exam_data, ensure_ascii=False, indent=2) + ";\n"

import os
output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data.js")
with open(output_path, "w", encoding="utf-8") as f:
    f.write(js_content)

print("Enriched data.js written successfully.")
